<?
// camera setup.
define('CAMERA_CODE_START'      , 0);
define('CAMERA_AE_ENABLE'       , 1);
define('CAMERA_EXP_LEVEL'       , 2);
define('CAMERA_A_FLICKER'       , 3);
define('CAMERA_AE_METERING'     , 4);
define('CAMERA_AWB_ENABLE'      , 5);
define('CAMERA_AWB_MODE'        , 6);
define('CAMERA_AWB_METHOD'      , 7);
define('CAMERA_R_GAIN'          , 8);
define('CAMERA_G_GAIN'          , 9);
define('CAMERA_B_GAIN'          , 10);
define('CAMERA_HUE'             , 11);
define('CAMERA_SATURATION'      , 12);
define('CAMERA_BRIGHTNESS'      , 13);
define('CAMERA_CONTRAST'        , 14);
define('CAMERA_SHARPNESS'       , 15);
define('CAMERA_MCTF_3DNR'       , 16);
define('CAMERA_LOCAL_EXP'       , 17);
define('CAMERA_BACKLIGHT'       , 18);
define('CAMERA_DN_MODE'         , 19);
define('CAMERA_SHUTTER'         , 20);
define('CAMERA_SLOW_SHUTTER'    , 21);
define('CAMERA_MIRROR'          , 22);
define('CAMERA_FLIP'            , 23);
define('CAMERA_GAIN'            , 24);
define('CAMERA_TDN_BW_LEVEL'    , 25);
define('CAMERA_TDN_COLOR_LEVEL' , 26);
define('CAMERA_RESP'            , 27);
define('CAMERA_CODE_END'        , 28);

$list  = array("START",
	"ae_en",
	"exp_level", 
	"a_flicker",
	"ae_meter",
	"awb_en",
	"awb_mode",
	"awb_method",
	"r_gain",
	"g_gain",
	"b_gain",
	"hue",
	"saturation",
	"brightness",
	"contrast",
	"sharpness",
	"mctf3dnr",
	"local_exp",
	"blc",
	"dnmode",
	"shutter",
	"sshutter",
	"mirror",
	"flip",
	"cam_gain",
	"tdn_bw_level",
	"tdn_color_level",
	"tdn_resp");
?>
