<?
// camera setup.
define('CAMERA_CODE_START'      , 0);
define('CAMERA_AE_ENABLE'       , 1);
define('CAMERA_EXP_LEVEL'       , 2);
define('CAMERA_A_FLICKER'       , 3);
define('CAMERA_AE_METERING'     , 4);
define('CAMERA_AWB_ENABLE'      , 5);
define('CAMERA_AWB_MODE'        , 6);
define('CAMERA_R_GAIN'          , 7);
define('CAMERA_G_GAIN'          , 8);
define('CAMERA_B_GAIN'          , 9);
define('CAMERA_HUE'             , 10);
define('CAMERA_SATURATION'      , 11);
define('CAMERA_BRIGHTNESS'      , 12);
define('CAMERA_CONTRAST'        , 13);
define('CAMERA_SHARPNESS'       , 14);
define('CAMERA_MCTF_3DNR'       , 15);
define('CAMERA_LOCAL_EXP'       , 16);
define('CAMERA_BACKLIGHT'       , 17);
define('CAMERA_DN_MODE'         , 18);
define('CAMERA_SHUTTER'         , 19);
define('CAMERA_SLOW_SHUTTER'    , 20);
define('CAMERA_MIRROR'          , 21);
define('CAMERA_FLIP'            , 22);
define('CAMERA_GAIN'            , 23);
define('CAMERA_TDN_BW_LEVEL'    , 24);
define('CAMERA_TDN_COLOR_LEVEL' , 25);
define('CAMERA_RESP'            , 26);
define('CAMERA_HDR_MODE'		, 27);
define('CAMERA_HDR_LEVEL'		, 28);
define('CAMERA_TDN_COLOR_HOUR'	, 29);
define('CAMERA_TDN_COLOR_MIN'	, 30);
define('CAMERA_TDN_BW_HOUR'		, 31);
define('CAMERA_TDN_BW_MIN'		, 32);
define('CAMERA_IRLED_ENABLE'    , 33);
define('CAMERA_SHUTTER_LIMIT'   , 34);
define('CAMERA_IRLED_STRENGTH'  , 35);
define('CAMERA_CODE_END'        , 36);


$list  = array("START",
	"ae_en",
	"exp_level", 
	"a_flicker",
	"ae_meter",
	"awb_en",
	"awb_mode",
	"r_gain",
	"g_gain",
	"b_gain",
	"hue",
	"saturation",
	"brightness",
	"contrast",
	"sharpness",
	"mctf3dnr",
	"local_exp",
	"blc",
	"dnmode",
	"shutter",
	"sshutter",
	"mirror",
	"flip",
	"cam_gain",
	"tdn_bw_level",
	"tdn_color_level",
	"tdn_resp",
	"hdr",
	"hdr_level",
	"color_hour",
	"color_min",
	"bw_hour",
	"bw_min",
	"ir_enabled",
	"shutter_limit",
	"ir_strength",
);
?>
