<?
// camera setup.
define('CAMERA_CODE_START'      		, 0);
define('CAMERA_THERMAL_COLOR'      		, 1);
define('CAMERA_THERMAL_FLIP'    		, 2);
define('CAMERA_THERMAL_MIRROR'      	, 3);
define('CAMERA_THERMAL_DENOISE'     	, 4);
define('CAMERA_THERMAL_META_DATA_ENABLE', 5);
define('CAMERA_THERMAL_TEMPERATURE_UNIT', 6);
define('CAMERA_CODE_END'        		, 7);


$list  = array("START",
	"thermal_color",
	"thermal_flip", 
	"thermal_mirror",
	"thermal_denoise",
	"thermal_meta_data_enable",
	"thermal_temperature_unit",
);
?>
